fix: pass multi to readme instead of command

diff --git a/.github/actions/generateOclifReadme/action.yml b/.github/actions/generateOclifReadme/action.yml
--- a/.github/actions/generateOclifReadme/action.yml
+++ b/.github/actions/generateOclifReadme/action.yml
@@ -10,8 +10,8 @@ inputs:
     required: true
   pre-release-identifier:
     description: The name of the prerelease channel (e.g. dev, beta)
-  command:
-    description: The command to run to generate the readme.
+  multi:
+    description: Create a different markdown page for each topic.
 
 runs:
   using: composite
@@ -44,13 +44,9 @@ runs:
       run: |
         yarn install
         yarn tsc
-        if [[ -n "${{ inputs.command }}" ]]; then
-          command="${{ inputs.command }}"
-        else
-          command="yarn oclif readme"
-        fi
-        ${command} \
+        yarn oclif readme \
           --no-aliases \
           --version ${{ steps.next-version.outputs.tag }} \
+          ${{ inputs.multi && '--multi' || '' }} \
           --repository-prefix "<%- repo %>/blob/<%- version %>/<%- commandPath %>" \
-          || echo "::warning::'${command}' failed. Check the logs."
+          || echo "::warning::'oclif readme' failed. Check the logs."
